# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 4afd4f2aee4db47484f9bc2fc35d4fbd0d988dd9bd2d90bb2dae757bf4d5a748c1032efd2903c946cd5461ca22dd1b5c97a0e98004b541974ffbf85e081f99a8

test:
  secret_key_base: d997bf4fa64b879da88cee7c9f9f10100aebb71bd76e0c25f35d660e8624fb99fb40ee62900d213d7534bd9b0db5f817261e7d89f6aa0399356c83dff0bb69e9

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
